### ISSUE TITLE
I can't seem to find the "run" button at the end of my code block

### ISSUE THREAD

**Issue by anonymousDog12** [JeepShen/vscode-markdown-code-runner#8]
<img width="399" alt="Screen Shot 2021-12-07 at 5 43 01 AM" src="https://user-images.githubusercontent.com/27938057/144967732-40ddc393-1a03-4eba-92e5-387512b0aab9.png">

Did I miss some steps? Thanks!

**Comment by polyglotdev** [comment]
@ChangyuYan you need to place your cursor inside that code block.  
![image](https://user-images.githubusercontent.com/28935096/184402628-b78c2670-963b-4910-a716-78f862c56ca1.png)

**Comment by anonymousDog12** [comment]
Gotcha. Thanks!
